### ISSUE TITLE
newest vector out of bounds

### ISSUE THREAD

**Issue by ysangkok** [pjones/cassava-streams#4]
Hi, thanks for the library, we're using it. But the upper dependency bounds are disallowing the newest version of e.g. the `vector` package.

**Comment by pjones** [comment]
@ysangkok Thank you for bringing this to my attention.  Would you be able to submit a patch or PR?

**Comment by ysangkok** [comment]
Thanks for the merge. It should be possible to revise the existing release to use the new bounds at https://hackage.haskell.org/package/cassava-streams/maintain

**Comment by pjones** [comment]
Thank you for that link.

I'm not sure how I feel about editing an existing release vs. just making a new release.  I'll look more into it and do one or the other in the next day or so.

**Comment by pjones** [comment]
Sorry about the delay.  I added a revision on Hackage.

**Comment by ysangkok** [comment]
Thank you! Much appreciated!
